services:
  app:
    build: .
    container_name: simple-python-server
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload --reload-include *
    ports:
      - 8081:80
    volumes:
      - .:/app